### PR TITLE
Updated anchor-attributes

### PR DESCRIPTION
**Pull request by mahesh471978**
Hi Loris, few anchor attributes are changed since you wrote this article, reference of which are given below.

- Changes regarding Error: https://project-serum.github.io/anchor/tutorials/tutorial-4.html#defining-a-program
- Changes regarding system_program, ProgramResult: https://project-serum.github.io/anchor/tutorials/tutorial-1.html#defining-a-program

### CODE REVIEW

**Comment by zappycode** [comment]
Thanks! This was super helpful

**Comment by lorisleiva** [comment]
Thanks that's awesome! I'll leave this open until I get the chance to update the articles as well otherwise I'll forget haha. But thanks again that's much appreciated! 🍺

**Comment by mahesh471978** [comment]
Hey Loris, it is me who said thanks for this awesome article you wrote, I gone through many documentations to learn solana development, and I am sure this is best of all.

This article is better than anchor's own documentation. (Actually, I think solana people should pay you for this, as I am sure this article is starting point for atleast 100 solana developer).

And I am glad you replied. 🙂

**Comment by silvestrevivo** [comment]
@lorisleiva I was trying both implementations but I get some errors. I went to the new docs and I did this: 

```
require!(topic.chars().count() <= 50, ErrorCode::TopicTooLong);
require!(content.chars().count() <= 280, ErrorCode::ContentTooLong);
```

Now I can retrieve the messages in the test and frontend. No idea why this is working and the solution above it doesn't. 

Thanks so much for this tutorial, is the best I found to learn Anchor/Solana. :)

**Comment by henryksarat** [comment]
I added this implementation and I can't run the test for just send tweet. 

When running the test for just the send tweet test (with no asserts) I get the error:

"Error: 4100: The declared program id does not match the actual program id"

I'm on a new mac and have two terminals open: 
Terminal 1: solana-test-validator --no-bpf-jit --reset 
Terminal 2: anchor test --skip-local-validator

**Comment by lorisleiva** [comment]
@silvestrevivo I had some issues with errors once when upgrading Anchor too. It was due to Anchor changing the index in which custom errors start. If your Anchor version on the Rust program didn't match the Anchor version used on the frontend then you'd have a mismatch. Not sure if this is what happened to you but hopefully that helps. 😊

**Comment by lorisleiva** [comment]
Articles updated, thank you! ❤️

**Comment by silvestrevivo** [comment]
@lorisleiva ah thanks so much! that's something that I should test.

**Pull request merged**
